### ISSUE TITLE
Confused by install instructions

### ISSUE THREAD

**Issue by folkertdev** [tylerwhall/zephyr-rust#26]
Hi, I've tried to follow your readme, but I think I'm stuck. I have on my machine

- an installation of the latest zephyr sdk
- an installation of zephyr following https://docs.zephyrproject.org/latest/getting_started/index.html
   I've confirmed that the `blinky` example works
- a fresh git clone of this repo, per the readme.

Now I want to build the example 

```
west build -p auto -b native_posix samples/rust-app/
```

But running `west build` in the `zephyr-rust` folder fails immediately (`build` is not a valid subcommand). I tried copying various things over into the `zephyr-rust/zephyr` folder but that ultimately failed too.

I'm suspecting the answer lies in `ZEPHYR_EXTRA_MODULES`, but I'm not sure what to do with it.

**Comment by tylerwhall** [comment]
With my limited knowledge of west, I think you just need to set the environment variable ZEPHYR_BASE to the path to zephyr. It seems `build` is an extension command that comes from the zephyr repo.

When it's working correctly `west help` shows the extension commands.
```
extension commands from project manifest (path: zephyr):
  completion:           display shell completion scripts
  boards:               display information about supported boards
  build:                compile a Zephyr application
  sign:                 sign a Zephyr binary for bootloader chain-loading
  flash:                flash and run a binary on a board
  debug:                flash and interactively debug a Zephyr application
  debugserver:          connect to board and launch a debug server
  attach:               interactively debug a board
  zephyr-export:        export Zephyr installation as a CMake config
                        package

```

Experimentally, it seems it picks up the extensions if you run west from within a subdirectory of the west project (containing a .west directory). If you run west from anywhere outside of there, the extension commands will not show up unless ZEPHYR_BASE is set.

The CMakeLists.txt in each sample also assumes ZEPHYR_BASE is set.

The next problem you will hit is native_posix is currently broken due to #21. I suggest using qemu_x86 or qemu_cortex_m3.

I added some Dockerfiles and scripts to automate validating builds. Those might serve as an example of what components are required.

https://github.com/tylerwhall/zephyr-rust/commit/011bad48a57bbdfa9bf225b2b586ed388232b1bd

Feel free to reply/reopen if you're still having trouble.
