### ISSUE TITLE
How up to date is this?

### ISSUE THREAD

**Issue by mkschreder** [tylerwhall/zephyr-rust#30]
I see that the last commit is in 2021.

Is there another repository where this development continues?

**Comment by tylerwhall** [comment]
The project is still in use at my company and just hasn't needed any updates recently.

I do hope to update at least the Rust compiler version soon. We haven't updated Zephyr in a couple years (still on 2.3) and it's not currently planned (as much as I would like to), so I haven't been inclined to proactively keep up with upstream Zephyr, as that would probably mean maintaining separate branches.

I would accept patches for newer Zephyr support. I would guess the 2.7 LTS would be a popular choice. I would try to keep one branch compatible with as many 2.x versions as possible, but I don't know if it's feasible to support from 2.3 to 2.7.

**Comment by mkschreder** [comment]
Thanks for your response Tyler. 

Would it at least be possible not to have to depend on only one particular rust version? Is it possible to somehow make updating rust versions easy?

**Comment by tylerwhall** [comment]
This requires adding a zephyr backend to the Rust libstd source at `library/std/src/sys/zephyr`. There are a few small changes outside of there. The `sys` APIs change on every version, and the version of the compiler is tied to libstd because it uses unstable features.

I just updated from 1.51 to 1.54 and it wasn't too difficult. They seem to be improving the APIs so there is less boilerplate. Maybe it will become easier to plug in out-of-tree platforms.

Upstreaming zephyr support to Rust would be ideal, but I don't know how to proceed because all the other supported platforms have stable ABIs. Zephyr's ABI changes based on config options (and the API is not very stable across zephyr versions, in my experience) so you need to have an end zephyr project with its config and the kernel source present to build the Rust bindings. Not sure how that would work with their automated builds and binary releases (rustup).

I'm planning to keep working on Rust updates soon.
